
THIS PROJECT IS ONLY AN EARLY DRAFT.

SAVED HERE FOR BACKUP. 

The code and doc may give you an idea of where the project is headed.  Nothing else. 

[2013-12-04 Wed]

* Why org-publish-meta?
:PROPERTIES:
:DATE:     <2013-12-03 Tue 07:21>
:END:

(To be written:  A few words about the motivation / background for the project.): 

** Why the name?
:PROPERTIES:
:DATE:     <2013-12-02 Mon 00:01>
:END: 

Because it extends org-publish.  It is "meta" in the sense of extracting org files from org files, and adding these to projects for publication with org-publish. 

The prefix used for functions in this package will be org-pm- as abbreviation of org-publish-meta-.

An alternative name - or subtitle - of this package could be "Zero Config", reflecting the premise of making a project publishable with the minimum amount of configuration specifications, and of creating a project for a single file even without any specifications at all.

** Motivation 1: Make it easier to configure projects for org-publish

** Motivation 2: Enable some of the nice features of o-blog

** Motivation 3: Keep the contents of several web-pages in one org-file

Advantages:  Better overview and editing.


** Motivation 4: Need to copy files or parts of files from current notes to different projects for publishing

Last but not least ... this was a major factor ... 

* Features
:PROPERTIES:
:DATE:     <2013-12-03 Tue 14:25>
:END:

** Auto-save org-publish-project-alist

** Automatic creation of projects with 0 configuration

** Simple customization of projects using in-file org-mode style nodes

** Multiple projects per file

** Any node in a file can be copied as separate file to any project

** Easy per-file customization of html export with properties and org-mode style nodes

** Inheritance of properties in sub-projects

** Publish same file or node to multiple projects

* Getting started
:PROPERTIES:
:DATE:     <2013-12-03 Tue 11:41>
:END:

