Ideas for further development.

* Further Features: Link Resolution, Templates

- =org-mode= style links to org-files or sections will break when exporting with =org-pm=, because sections are exported to different files.  It is possible to use custom id's to sections in order to re-map links to the correct files (see =org-id=).

- It would be handy to define templates of content inside an org-mode file, which could then be inserted at any point in the file for export, and would furthermore be able to execute lisp code for dynamic content.

The overall approach is to port some of the functionality of o-blog to org-pm.

https://github.com/renard/o-blog

Both =o-blog= and =org-pm= export sections of an org-mode file to separate html-files.

=o-blog= implements a mechanism for including templates in the export file and for executing lisp code in those templates, by marking the code with tag =<lisp>=.

Another feature that

* Templates
:PROPERTIES:
:DATE:     <2014-02-18 Tue 08:08>
:END:

Use includes and export filters to implement lisp-interpreted templates?

** org-mode includes
http://orgmode.org/manual/Include-files.html

** o-blog <lisp> mechanism
See function =ob-eval-lisp= in file =o-blog.el= of =o-blog=.
