* TUTORIAL
:PROPERTIES:
:DATE:     <2013-12-18 Wed 09:30>
:END:

** Installation
:PROPERTIES:
:DATE:     <2013-12-18 Wed 09:31>
:END:

Org-publish-meta is currently available only from github.
After downloading and placing it in your load path
run the following to make org-pm available to EMACS.

#+BEGIN_SRC elisp
(require 'org-pm)
#+END_SRC

** The Menu

Command org-pm-menu lists all commands of org-pm, and lets you execute any selected command from a menu presented in the mini-buffer.

** Defining a project

Three steps are required to define a project:

1. Insert the project definition in an org-mode buffer (=org-pm-insert-new-project=)
2. (Optional:) Edit the project definition to customize parameters
3. Parse the project definition and add the project in =org-publish-project-alist= (=org-pm-make-projects=)

Here are the steps in detail:

*** Insert project definition code to buffer

Command: =org-pm-insert-new-project= (=H-m n=).

The command asks for the name of the project, the base directory and the html directory of the project.  If the directories that are entered in the minibuffer do not exist, org-pm creates them.

Org-pm then inserts a project definition template into the current buffer, as subsection of a section marked with the tag "PROJECT_DEFS".   If such a section does not yet exist, org-pm creates the section at the end of the buffer.

Here is an example of such a section:

*** Editing the properties of a project

*** Updating the project

Command =org-pm-make-projects= (=H-m m=).

The command

** Adding and removing sections to/from projects
*** Add a section to a project
:PROPERTIES:
:DATE:     <2013-12-18 Wed 09:51>
:END:

Command: =org-pm-add-section-to-project= (=H-m a=).

The command org-pm-add-section-to-project lets the user select a project from a list of existing projects displayed in the menu buffer, and adds the current org-mode section of the current buffer to the selected project.  If there is no project defined, the command offers to create a default project (see below).

*** Remove a section from a project
:PROPERTIES:
:DATE:     <2013-12-18 Wed 10:16>
:END:

Command: org-pm-remove-section-from-project
Keyboard shortcut: H-m r.

The command org-pm-remove-file-from-project lets the user select a project from a list of projects to which this project has been added, displayed in the menu buffer, and removes the file of the current buffer from the selected project.  It also removes the corresponding property or tag from the current buffer.

** Publishing a project
:PROPERTIES:
:DATE:     <2013-12-18 Wed 10:43>
:END:

*** Automatic parsing and copying with standard emacs/org-mode saving and publishing commands

If the
- Save any buffers th

*** Explicit execution of parsing and copying files through commands

If the auto-parse option is enabled (see Tutorial section 1: Installation and basic configuration), then all you need to do to update the configuration of any file that you want to include in org-pm is save it.  The file is then ready for publication according to any specifications included in the file contents.

If the auto-parse option is not enabled, then call command org-pm-parse-file to update any project definitions contained in the file and also register any parts of the file (nodes, or the file itself) which are marked to be copied to any projects.

If the auto-copy option is enabled (see Tutorial section 1: Installation and basic configuration), then org-pm

** Adding the containing file to a project definition
:PROPERTIES:
:DATE:     <2013-12-18 Wed 10:43>
:END:

** Adding a node of a file to a project
:PROPERTIES:
:DATE:     <2013-12-18 Wed 10:43>
:END:
