* TUTORIAL
:PROPERTIES:
:DATE:     <2013-12-18 Wed 09:30>
:END:

** Installation
:PROPERTIES:
:DATE:     <2013-12-18 Wed 09:31>
:END:

Org-publish-meta is currently available from github at [[https://github.com/iani/org-publish-meta/]] and from bitbucket at [[https://bitbucket.org/iannis_zannos/org-publish-meta]]

Download the source and then:

Place org-pm.el in a folder that is member of the list contained in variable =load-path=,
or add the path where =org-pm=.el is to =load-path= like this:

: (add-to-list 'load-path "/path/to/org-publish-meta")

Install required package =grizzl= from online repositories:

: (package-install 'grizzl)

Then run this to install org-pm:

: (require 'org-pm)

Once org-pm is installed, type H-m H-m to open a menu of commands.  (H = Hyper = the function key on Mac).  Alternatively run command =org-pm-menu=.

** The Menu

Type H-m H-m (Function-key marked "fn" and m, twice) to open the command menu (=org-pm-menu=).  Command =org-pm-menu= lists all commands of org-pm, and lets you execute any selected command from a menu presented in the mini-buffer.  The commands are:

|  1 | org-pm-insert-new-project              |
|  2 | org-pm-make-projects                   |
|  3 | org-pm-project-def-list                |
|  4 | org-pm-add-section-to-project          |
|  5 | org-pm-remove-section-from-project     |
|  6 | org-pm-edit-project-tag-lists          |
|  7 | org-pm-export                          |
|  8 | org-pm-open-target-of-this-file        |
|  9 | org-pm-open-source-of-this-file        |
| 10 | org-pm-source-file-menu                |
| 11 | org-pm-target-file-menu                |
| 12 | org-pm-publish                         |
| 13 | org-pm-show-project-definition-section |
| 14 | org-pm-edit-project-template           |
| 15 | org-pm-list-duplicate-project-defs     |
| 16 | pm/edit-duplicate-project-def          |
| 17 | org-pm-post-project-def                |
| 18 | org-pm-load-project-data               |
| 19 | org-pm-save-project-data               |
| 20 | org-pm-reset-project-list              |
| 21 | org-pm-edit-saved-project-data         |
#+TBLFM: $1=@-1+1::@1$1=1

** =org-pm-insert-new-project=: Create a new project

- =H-m n= (=M-x org-pm-insert-new-project=) :: Asks for name of new project, base-directory, and publishing-directory.

Note: =base-directory= is no longer used in the newest version of the org-publish-meta package. =org-pm-export= publishes directly from the current buffer to =publishing-directory=.

1. Insert the project definition in an org-mode buffer (=org-pm-insert-new-project=)
2. (Optional:) Edit the project definition to customize parameters
3. Parse the project definition and add the project in =org-publish-project-alist= (=org-pm-make-projects=)

Here are the steps in detail:

*** Insert project definition code to buffer

Command: =org-pm-insert-new-project= (=H-m n=).

The command asks for the name of the project, the base directory and the html directory of the project.  If the directories that are entered in the minibuffer do not exist, org-pm creates them.

Org-pm then inserts a project definition template into the current buffer, as subsection of a section marked with the tag "PROJECT_DEFS".   If such a section does not yet exist, org-pm creates the section at the end of the buffer.

Here is an example of such a section:

*** Editing the properties of a project

*** Updating the project

Command =org-pm-make-projects= (=H-m m=).

The command

** Adding and removing sections to/from projects
*** Add a section to a project
:PROPERTIES:
:DATE:     <2013-12-18 Wed 09:51>
:END:

Command: =org-pm-add-section-to-project= (=H-m a=).

The command org-pm-add-section-to-project lets the user select a project from a list of existing projects displayed in the menu buffer, and adds the current org-mode section of the current buffer to the selected project.  If there is no project defined, the command offers to create a default project (see below).

*** Remove a section from a project
:PROPERTIES:
:DATE:     <2013-12-18 Wed 10:16>
:END:

Command: org-pm-remove-section-from-project
Keyboard shortcut: H-m r.

The command org-pm-remove-file-from-project lets the user select a project from a list of projects to which this project has been added, displayed in the menu buffer, and removes the file of the current buffer from the selected project.  It also removes the corresponding property or tag from the current buffer.

** Publishing a project
:PROPERTIES:
:DATE:     <2013-12-18 Wed 10:43>
:END:

*** Automatic parsing and copying with standard emacs/org-mode saving and publishing commands

If the
- Save any buffers th

*** Explicit execution of parsing and copying files through commands

If the auto-parse option is enabled (see Tutorial section 1: Installation and basic configuration), then all you need to do to update the configuration of any file that you want to include in org-pm is save it.  The file is then ready for publication according to any specifications included in the file contents.

If the auto-parse option is not enabled, then call command org-pm-parse-file to update any project definitions contained in the file and also register any parts of the file (nodes, or the file itself) which are marked to be copied to any projects.

If the auto-copy option is enabled (see Tutorial section 1: Installation and basic configuration), then org-pm

** Adding the containing file to a project definition
:PROPERTIES:
:DATE:     <2013-12-18 Wed 10:43>
:END:

** Adding a node of a file to a project
:PROPERTIES:
:DATE:     <2013-12-18 Wed 10:43>
:END:
